alphabetic:
  iPad:
    floating: "alphabetic_26_portrait"
    landscape: "ipad_alphabetic_26_landscape"
    portrait: "ipad_alphabetic_26_portrait"
  iPhone:
    landscape: "alphabetic_26_landscape"
    portrait: "alphabetic_26_portrait"
author: "BlackCCCat"
name: "万象键盘"
numeric:
  iPad:
    floating: "numeric_9_portrait"
    landscape: "ipad_numeric_9_landscape"
    portrait: "ipad_numeric_9_portrait"
  iPhone:
    landscape: "numeric_9_landscape"
    portrait: "numeric_9_portrait"
panel:
  iPhone:
    landscape: "panel_landscape"
    portrait: "panel_portrait"
pinyin:
  iPad:
    floating: "pinyin_26_portrait"
    landscape: "ipad_pinyin_26_landscape"
    portrait: "ipad_pinyin_26_portrait"
  iPhone:
    landscape: "pinyin_26_landscape"
    portrait: "pinyin_26_portrait"
temp_pinyin:
  iPhone:
    landscape: "temp_pinyin_landscape"
    portrait: "temp_pinyin_portrait"
